apiVersion: v2
name: backpressure-example
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: prometheus-adapter
    version: 2.8.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus
    version: 12.0.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: metrics-server
    version: 2.11.4
    repository: https://charts.helm.sh/stable
